In [14]:
import pandas as pd

### Series

In [15]:
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
s = pd.Series(arr)
print(s)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64


In [41]:
s = pd.Series(arr, dtype = 'int32')
print(s) #'' 쓰는거 유의해주기 

0    50
1    51
2    52
3    53
4    54
dtype: int32


In [19]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series(person)
print(s)

0     kim
1     lee
2    park
3    hong
dtype: object


In [20]:
s = pd.Series([2, 3, 4, "99"])
print(s)

0     2
1     3
2     4
3    99
dtype: object


### indexing

In [21]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series(person)

In [23]:
s.index #시작점, 끝나는 점, 단계  (0,1,2,3)으로 

RangeIndex(start=0, stop=4, step=1)

In [27]:
s[2] #음수 인덱싱은 불가능 (cf: 파이썬은 가능했었음)

'park'

In [28]:
s = pd.Series(person, index = ['a', 'b', 'c', 'd'])
print(s)
#인덱스라는 키 값을 주지 않으면 0,1,2,3이 주어짐 

a     kim
b     lee
c    park
d    hong
dtype: object


In [29]:
s['a'] #인덱싱 방법

'kim'

In [32]:
s.index #object의 형식으로 바뀐걸 볼수 있다. 일반적으로 숫자로 접근하지만,데이터프레임 열로 접근할때 오브젝트로 가능

Index(['a', 'b', 'c', 'd'], dtype='object')

In [34]:
s.values #현재 데이터를 value만 가지고 나옴

array(['kim', 'lee', 'park', 'hong'], dtype=object)

In [36]:
s.ndim #dimension

1

In [37]:
s.shape

(4,)

### NaN(Not A Number)
- 결측치

In [38]:
s = pd.Series(person + [np.nan])
print(s)

0     kim
1     lee
2    park
3    hong
4     NaN
dtype: object


In [40]:
arr = np.arange(50, 55)
s = pd.Series(arr, dtype = 'float32')
print(s)

0    50.0
1    51.0
2    52.0
3    53.0
4    54.0
dtype: float32


In [42]:
f = ['바나나', np.nan, '사과', '포도', '복숭아']
s = pd.Series(f, index=list('가나다라마'))
print(s)

가    바나나
나    NaN
다     사과
라     포도
마    복숭아
dtype: object


In [44]:
s[['다', '나']] #fancy indexing

다     사과
나    NaN
dtype: object

In [46]:
s.iloc[[2,3]]
s[['다', '라']]
#intger로 접근 vs 인덱싱으로 접근 

다    사과
라    포도
dtype: object

### bool

In [47]:
s[[True, False, True, False, True]]

가    바나나
다     사과
마    복숭아
dtype: object

In [51]:
arr = np.arange(5, 20)
s= pd.Series(arr)
print(s)

0      5
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
dtype: int64


In [52]:
s < 10 #각각 너 10보다 작냐 ? 

0      True
1      True
2      True
3      True
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [55]:
s[s < 10] 

0    5
1    6
2    7
3    8
4    9
dtype: int64

### 결측치 처리 

In [56]:
s = pd.Series([2, 5, 2, 1, np.nan, 2, 4, np.nan])
print(s)

0    2.0
1    5.0
2    2.0
3    1.0
4    NaN
5    2.0
6    4.0
7    NaN
dtype: float64


In [58]:
s[s.isnull()] #어떤 위치가 결측치인지 ? 
#isnull - tf로 이뤄지는 것으로 만들어줌, 거기서 결측치 뽑아내주기 

4   NaN
7   NaN
dtype: float64

In [59]:
s.isna() #nan을 true로 골라주셈 #notnull을 골라주셈

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7     True
dtype: bool

In [60]:
s[s.isna()]

4   NaN
7   NaN
dtype: float64

In [61]:
s[s.notnull()] #isnull과 반대의 상황

0    2.0
1    5.0
2    2.0
3    1.0
5    2.0
6    4.0
dtype: float64

In [62]:
s[1:3]

1    5.0
2    2.0
dtype: float64

### DataFrame

In [63]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [64]:
df = pd.DataFrame(arr)
df

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [67]:
df = pd.DataFrame(arr, columns = ['가', '나', '다'], index=['a','b','c'])
df                     

가  나  다
a  0  1  2
b  3  4  5
c  6  7  8

In [100]:
df = pd.DataFrame({
    'name' : ['kim', 'lee', 'park'], 
    'age' : [10, 15, 20], 
    'location' : ['서울', '도쿄', '엘에이']})
df

#만드는거 조심 

name  age location
0   kim   10       서울
1   lee   15       도쿄
2  park   20      엘에이

In [101]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [102]:
df.columns

Index(['name', 'age', 'location'], dtype='object')

In [103]:
df.values

array([['kim', 10, '서울'],
       ['lee', 15, '도쿄'],
       ['park', 20, '엘에이']], dtype=object)

In [104]:
df.dtypes

name        object
age          int64
location    object
dtype: object

In [105]:
df.T #인덱스 위치와 칼럼 위치를 바꾸는 것

0    1     2
name      kim  lee  park
age        10   15    20
location   서울   도쿄   엘에이

### column

In [106]:
df.index = list('abc')
df

name  age location
a   kim   10       서울
b   lee   15       도쿄
c  park   20      엘에이

In [107]:
df['name'] #잘못한거 없는거 같은데 에러가 엄청 길게 뜸 ㅠㅠ 

a     kim
b     lee
c    park
Name: name, dtype: object

In [108]:
df[['name', 'location']]

name location
a   kim       서울
b   lee       도쿄
c  park      엘에이

In [109]:
df.rename(columns={'location': 'hometown'})


name  age hometown
a   kim   10       서울
b   lee   15       도쿄
c  park   20      엘에이